### ISSUE TITLE
.LESS Validation Removed

### ISSUE THREAD

**Issue by someyoungideas** [madskristensen/WebEssentials2012#10]
There are a couple scenarios when writing .less that bring up validation errors in nested classes that are not necessary. The first is relatively small so it may not be necessary, but the second one is more of a hassle. 

The first is the case of a nested class that is being attached with "&" and followed with a hyphen. An example : 

```
.myclassname {
    &-addon{

    }
}
```

The second one is that .less files complain if you have nested media queries. This one is a little more of a sore because it throws an unexpected error and then every style rule that is placed within the media query also comes back with an error. An example : 

```
.myclassname {
    @media(min-width: 1200px) {
        margin: 0 auto;
    }
}
```

I forgot to mention that both of these issues still compile correctly to .css files because they are fitting .less syntax. The issue would have to do more with less visual errors in the files themselves. Hope these make sense, you can let me know if something is confusing about them.

**Comment by madskristensen** [comment]
Both issues cannot be fixed by WE. They have been fixed for VS2013 and will be in a future update though. No update is coming to VS2012
