### ISSUE TITLE
CSS Newline Characters Changed

### ISSUE THREAD

**Issue by flamewave** [madskristensen/WebEssentials2012#11]
This may be a bug in whatever minimize engine you're using instead of in WebEssentials, but figured I'd report it anyways so you can check.

When using the "content" CSS property, if you specify the CSS new line character of "\a", when minimized, it gets changed to "\n", which breaks the CSS because "\n" is not recognized as a new line character by CSS (see http://www.w3.org/TR/CSS2/syndata.html#strings).

For example, the following CSS:
div:after { content: "\a"; white-space: pre; }

is minimized to this:
div:after{content:"\n";white-space:pre}

**Comment by ronklogan** [comment]
It's definitely an AjaxMin bug that a string with "\a" in it gets replaced with a string containing "\n" -- it shouldn't be changing characters within a string like that.

That said, I believe you are misreading the spec. A _raw_ line break is indeed not allowed inside strings in CSS. But escaped line breaks specifically are -- and "\n" is an escaped line break, and perfectly valid CSS. Granted, as I said before it's not the RIGHT line break since your string has a "\a" in it. I'll definitely get that fixed. But AjaxMin isn't generating _invalid_ CSS [just not the right CSS for the input].

**Comment by ronklogan** [comment]
Aw, shucks! I'm both right and wrong, all at the same time! :)

So if you are interested, you can open up that CSS Spec link you have there and scroll up to Section 4.1.1 "Tokenization." You'll see the syntax for a string token (two actually; one for single-quote delimited and one for double-quote delimited):

```
string1  \"([^\n\r\f\\"]|\\{nl}|{escape})*\" 
string2  \'([^\n\r\f\\']|\\{nl}|{escape})*\' 
```

The \n and the \a sequences would both fall under {escape}, which is defined as:

```
escape  {unicode}|\\[^\n\r\f0-9a-f] 
```

The \n would be that second part -- a backslash followed by something that is neither a raw line-feed nor a hexadecimal digit. For the \a, we follow into {unicode}:

```
unicode  \\[0-9a-f]{1,6}(\r\n|[ \n\r\t\f])? 
```

The \a falls under the first part: \[0-9a-f]{1,6} and gives the Unicode value 10.

So in the syntax, a "\n" sequence is a valid syntax element inside a string -- but what does it _mean_? AjaxMin was assuming \n was an ASCII-10, in a similar manner to \t being an ASCII-9, \r being an ASCII-13, etc. If that's the case, then \a is equivalent to \n and there is no bug here. HOWEVER, I don't see anywhere in the spec where an escape sequence like \n has a character value of 10! I'm going to keep reading to see if I'm just not seeing it right away, but it might be a bug that AjaxMin is assuming any particular control value in \t, \n, \r, \f sequences (or whatever other ones it may be using at the moment).

**Comment by ronklogan** [comment]
Yeah, I think a \n is just an escaped "n" character! There are no special single-character escape sequences in CSS strings as there are in JavaScript. The bottom of 4.1.3 says:

Note: Backslash escapes are always considered to be part of an identifier or a string (i.e., "\7B" is not punctuation, even though "{" is, and "\32" is allowed at the start of a class name, even though "2" is not). 
The identifier "te\st" is exactly the same identifier as "test".

I've been doing it wrong for years! This is an excellent bug, by the way. :D

**Comment by ronklogan** [comment]
This should be fixed in release 5.6 of AjaxMin.

**Comment by madskristensen** [comment]
I'll keep the bug here to remind me to update AjaxMin to 5.6 whenever it's ready. Thanks Ron!

**Comment by ronklogan** [comment]
Oh, I released it this morning.

Sent from my Windows Phone

**Comment by madskristensen** [comment]
I updated the NuGet package. Thanks Ron!!!
