### ISSUE TITLE
LESS document formatting does not respect CSS brace settings

### ISSUE THREAD

**Issue by prosser** [madskristensen/WebEssentials2012#16]
Repro:
1. Open VS2013 RTM with Web Essentials 2013 1.2 (11/12/2013) installed.
2. Set CSS brace positions to "compact" (Tools > Options > Text Editor > CSS > Advanced > Brace Settings = "Compact")
3. Open a LESS document
4. Format the document (CTRL-K, CTRL-D)

Expected:
Settings should be respected.

Observed:
"Expanded" format is always used.

**Comment by madskristensen** [comment]
This is a not a Web Essentials issue, but a VS issue. We've fixed it for VS, so it will be in an update coming out at some point in the future.
