### ISSUE TITLE
Nested @media Queries in LESS are still not working

### ISSUE THREAD

**Issue by mefcorvi** [madskristensen/WebEssentials2012#21]
Hello,

It seems that support of nested media queries are broken. I'm using Web Essentials v.3.3.5 and editor shows "Unexpected '@' block in the style rule" for the following code:

```
.parent {
    @media (min-width: 350px) {
        position: fixed;
    }
 }
```

I believe that it's broken for a long time regarding to http://webessentials.uservoice.com/forums/140520-general/suggestions/3226209-nested-media-queries-in-less

Thank you,
Bulat Aykaev.

**Comment by madskristensen** [comment]
This has been fixed in the VS code and will be part of a future update to VS2013. It is not a WE issue or one that can be fixed by WE.
