### ISSUE TITLE
VS2012 Crashes with JavaScript Language Service error (.coffee)

### ISSUE THREAD

**Issue by brcaswell** [madskristensen/WebEssentials2012#23]
First Some relative(ish) Info: (From 'HELP' > 'About ...')
Microsoft Visual Studio Premium 2012 Version 11.0.60610.01 Update 3
(product installed) Web Developer Tools 1.2.40308.0 

When viewing a .coffee file (after saving/compiling). I'm presented with 2 viewports, my coffee file source, and the output js (I suspect)..

![image](https://f.cloud.github.com/assets/967010/1617993/35380a5e-5626-11e3-8eb5-ea299f2472e3.png)

VS crashes If and when I click on an empty line (or text line node) on the right viewport - the output view..

If I click on a line that contains text, the error does not occur.. (as demonstrated by the text selection)

![image](https://f.cloud.github.com/assets/967010/1618020/c496b45c-5626-11e3-9896-abb751f43295.png)

error report... 
![image](https://f.cloud.github.com/assets/967010/1618027/f6a5d784-5626-11e3-9edc-0d537c23487a.png)

**Comment by brcaswell** [comment]
opps.. wrong printscreen hotkey combo :+1:

**Comment by brcaswell** [comment]
I created a bug report at https://connect.microsoft.com/VisualStudio/feedback/details/809646/clr20r3-system-argumentnullexception-in-microsoft-visualstudio-jsls-webextension2012

**Comment by madskristensen** [comment]
This has been fixed
