### ISSUE TITLE
Implicit tag names in an UL element

### ISSUE THREAD

**Issue by mauricedb** [madskristensen/WebEssentials2012#32]
According to the Emmet docs at http://docs.emmet.io/cheat-sheet/ the code "ul>.class" should expand to:

```
<ul>
    <li class="class"></li>
</ul>
```

However with WebEssentials 2012 this expands to:

```
<ul>
    <div class="class"></div>
</ul>
```

Adding an DIV element to an UL element is invalid and doens't really make sense.

**Comment by madskristensen** [comment]
This issue should not be here, but at the ZenCoding component (which is a standalone library) https://github.com/madskristensen/zencoding/
