### ISSUE TITLE
Add support for .jshintrc files

### ISSUE THREAD

**Issue by sadiebest** [madskristensen/WebEssentials2012#33]
For JSHint we use a .jshintrc file for sharing configuration: http://www.jshint.com/docs/#usage

This has been added to WebEssentials2013.

Are there any plans to include it in WebEssentials2012?

**Comment by allonhadaya** [comment]
+1 -- many developers do not have the option of using 2013

**Comment by madskristensen** [comment]
There is not. WE2012 doesn't use Node.js at all, so it would be a huge undertaking to port it
