### ISSUE TITLE
CSS Minification broken on Chrome 32

### ISSUE THREAD

**Issue by ThanosSiopoudis** [madskristensen/WebEssentials2012#39]
Hi there,
I'm compiling a set of less files in a single css file and minifying it, everything was working fine until Chrome was updated to version 32 last night. My media queries are no longer working with the minified css, but they work fine with the non minified one. That only happens on Chrome 32. Chrome 31, Firefox, Safari and IE all work fine.

Minifying my file through YUI compressor also works fine.

Thanks

**Comment by madskristensen** [comment]
This was just fixed in AjaxMin and will be in the next update to WE2012
