### ISSUE TITLE
Output generation failed when incorrect typescript file in project.

### ISSUE THREAD

**Issue by samjudson** [madskristensen/WebEssentials2012#43]
Hi

I've got this issue where an invalid Typescript file is causing the typescript generation to fail. 

I know why its failing (after much investigation) I just wonder if the error could be better.

If you have a file which is designed to be used under a module environment, such as below:

export class Test1 {
}

If this file is in a project which is not configured to use module generation (in my scenarios I was new to Typescript and didn't realise you didn't need to 'export' if you weren't inside a module) then you see the error "Output generation failed" in the visual studio status bar, but no other indication of the error or what is causing it. This happens when you try to save any file in the project, not just the one with the issue.

Let me know if you need any more details.

**Comment by madskristensen** [comment]
The compilation of TypeScript isn't handled by Web Essentials, but by the official TypeScript tooling. You should raise the bug with them

**Comment by samjudson** [comment]
If i build the project i see the error in the error window. If i simply save it i get only the status bar update. I've already raised it on the typescript codeplex site and i thought it sounded more like a web essentials issue. I could be wrong.

https://typescript.codeplex.com/workitem/2109
