### ISSUE TITLE
How To: exclude less files?

### ISSUE THREAD

**Issue by ghost** [madskristensen/WebEssentials2012#49]
I have a structure where 10 less files are imported into main.less

```
main.less
    ı-- main.css
modules [dir]
     mod-1.less
     mod-2.less
     ...
```

I'd like to auto-generate main.css from main.less every time a less file is saved, but not generate individual mod-x.css files for each less file. How do I do this?

**Comment by madskristensen** [comment]
add an underscore as the first character in the file name, for example `_mod-1.less`
