### ISSUE TITLE
[FEA] Collapse region to definitions with shortcut Ctrl+M, O

### ISSUE THREAD

**Issue by jerone** [madskristensen/WebEssentials2012#6]
In VS2012 there's a common shortcut (Ctrl+M, O) to "Collapse to Definitions" (EDIT > Outlining). For C# when executing this function all regions on that file will be collapsed.
Is it possible to include CSS regions as well?

**Comment by am11** [comment]
I guess in order to have the Outlining menu item as well as the corresponding shortcuts, the best place to request this feature would be connect. I just [reported](https://connect.microsoft.com/VisualStudio/feedback/details/806681/vs2012-to-support-css-collapsible-region) it there.
