### ISSUE TITLE
Less compiler interprets //** as the start of a C style comment

### ISSUE THREAD

**Issue by BillWagner** [madskristensen/WebEssentials2012#63]
Strangely enough, this only happens when you have selected the C++ profile for Visual Studio.

In that case, the less compiler will not compile the bootstrap source, because files like variables.less have single line comments that start with //**. The compiler is assuming that's the start of a C style multi line comment, and views the rest of the file as a comment.

**Comment by madskristensen** [comment]
This should not be affected by the C++ VS profile. There was a bug in the LESS editor in VS that would mark //*\* invalid, but that was fixed in VS2013 Update 2. Can you please confirm that it is the compiler and not the editor that has the error?

**Comment by BillWagner** [comment]
@madskristensen The compiler does have the error in that version. The output bootstrap.css file would not get generated.

That behavior is also fixed with WebEssentials 2.0, so maybe it was related?

**Comment by madskristensen** [comment]
I don't think it was related. The LESS editor in VS and the compiler are completely separate. They don't know of each other's existence even. So does it work now in 2.0 and can this ticket be closed?

**Comment by BillWagner** [comment]
@madskristensen  Yes, it works in 2.0.  Closing. Thank you for looking into it.
