### ISSUE TITLE
Is the 2012 version abandoned?

### ISSUE THREAD

**Issue by stijnherreman** [madskristensen/WebEssentials2012#65]
No commits since 25th of February, a bunch of open issues.

I'm getting really frustrated with daily crashes caused by https://github.com/madskristensen/WebEssentials2012/issues/61 especially because I don't even have the single TS feature that's still left in the extension enabled.

Is this version abandoned? Is there an active fork? Is there a roadmap?

I'm not asking to immediately fix all the issues, I'd just like to know where this is headed.

**Comment by madskristensen** [comment]
It is not actively being developed anymore by me and no one sends pull requests. If someone want to submit code, then I'd release a new version, but no one is.

**Comment by stijnherreman** [comment]
OK, thanks for the info :)

**Comment by LordDelacroix** [comment]
New release on 9/10/2014

Added support for .weignore files
Updated NuGet packages

Broke the continuing problem following a build: 

9/12/2014 8:04:19 AM: The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))
   at EnvDTE.Properties.Item(Object index)
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
   at EnvDTE.Properties.Item(Object index)
   at MadsKristensen.EditorExtensions.ProjectHelpers.GetRootFolder()
