### ISSUE TITLE
less files not previewing after visual studio reinstall

### ISSUE THREAD

**Issue by robYoungManchester** [madskristensen/WebEssentials2012#66]
After re-installing visual studio 2012 I found my less files were no longer previewing or compiling within VS.  Re-Installing web essentials 2012 didn't fix this problem.  When I right click on a less and select "Open with" the less editor is not listed.  However, tools -> options web essentials does list the less file as an acceptable file type and states that previewing is enabled.

I could associate the less file extension manually within VS using the open with function but would need to know the location of the less editor executable installed by web essentials.

**Comment by madskristensen** [comment]
You need to install Visual Studio 2012 Update 2 or later for the LESS editor to be present
