### ISSUE TITLE
Css bundles for VS 2012/2015 No Documentation on the Website

### ISSUE THREAD

**Issue by squadwuschel** [madskristensen/WebEssentials2012#86]
Hi,

when I check this page and try to select VS 2012 or 2015 there is no Documentation avavialbe only for 2013 is this feature missing in 2015 or is the documentation not up to date?

http://vswebessentials.com/features/bundling#

thx SquadWuschel

**Comment by madskristensen** [comment]
It's not supported in WE 2015
