### ISSUE TITLE
About GetClassificationsSpans

### ISSUE THREAD

**Issue by sebagomez** [madskristensen/WebEssentials2012#90]
I have a question about your code in the [GetClassificationSpans](https://github.com/madskristensen/WebEssentials2012/blob/31c2b578efed1eaf941c58fae0a88dc97e19cfec/EditorExtensions/Classifications/AppCache/AppCacheClassifier.cs) function.
I'm working on my own extension to provide syntax coloring on prolog source code files, called [VSProlog](https://github.com/sebagomez/vsprolog). The problem I'm facing is that I want to implement comment block coloring (/\* */) which just like C++ and the like, the start block (/*) can be in a line of code and the close block (*/) can be placed many lines below.
I had an approach where when I got a span, I get the line and check for every line before that one to see if there's a start block, in that case, that line is also a comment. The thing is, that's too expensive and freezes VS for a second... so I thought I could just check for the previous line, if that line is a comment, i'm also in a comment. But I don't know how to do that, because I can get the previously returned classifications spans.
I hope I made myself clear, any tip of advice would be greatly appreciated. 
Regards

**Comment by madskristensen** [comment]
You probably need to decouple the parser/lexer and the classifier. The right place to ask these questions is at https://gitter.im/Microsoft/extendvs

**Comment by sebagomez** [comment]
cool thanks!
